//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarClient.CarService {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CarType", Namespace="http://schemas.datacontract.org/2004/07/CarService")]
    public enum CarType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Car = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TruckCar = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PassengerCar = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CarService.ICarService")]
    public interface ICarService {
        
        // CODEGEN: Контракт генерации сообщений с операцией SetCar не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/SetCar", ReplyAction="http://tempuri.org/ICarService/SetCarResponse")]
        CarClient.CarService.SetCarResponse SetCar(CarClient.CarService.CarInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/SetCar", ReplyAction="http://tempuri.org/ICarService/SetCarResponse")]
        System.Threading.Tasks.Task<CarClient.CarService.SetCarResponse> SetCarAsync(CarClient.CarService.CarInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/GetCar", ReplyAction="http://tempuri.org/ICarService/GetCarResponse")]
        CarClient.CarService.CarInfo GetCar(CarClient.CarService.CarRequest request);
        
        // CODEGEN: Идет формирование контракта на сообщение, так как операция может иметь много возвращаемых значений.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/GetCar", ReplyAction="http://tempuri.org/ICarService/GetCarResponse")]
        System.Threading.Tasks.Task<CarClient.CarService.CarInfo> GetCarAsync(CarClient.CarService.CarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CarInfoWrapper", WrapperNamespace="http://in1clickdomain.com", IsWrapped=true)]
    public partial class CarInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public double Capacity;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int Id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Model;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int Passengers;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public CarClient.CarService.CarType Type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string Vendor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public int Year;
        
        public CarInfo() {
        }
        
        public CarInfo(double Capacity, int Id, string Model, int Passengers, CarClient.CarService.CarType Type, string Vendor, int Year) {
            this.Capacity = Capacity;
            this.Id = Id;
            this.Model = Model;
            this.Passengers = Passengers;
            this.Type = Type;
            this.Vendor = Vendor;
            this.Year = Year;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetCarResponse {
        
        public SetCarResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CarRequest", WrapperNamespace="http://in1clickdomain.com", IsWrapped=true)]
    public partial class CarRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://in1clickdomain.com")]
        public string LicenseKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://in1clickdomain.com", Order=0)]
        public int Id;
        
        public CarRequest() {
        }
        
        public CarRequest(string LicenseKey, int Id) {
            this.LicenseKey = LicenseKey;
            this.Id = Id;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICarServiceChannel : CarClient.CarService.ICarService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CarServiceClient : System.ServiceModel.ClientBase<CarClient.CarService.ICarService>, CarClient.CarService.ICarService {
        
        public CarServiceClient() {
        }
        
        public CarServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CarServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarClient.CarService.SetCarResponse CarClient.CarService.ICarService.SetCar(CarClient.CarService.CarInfo request) {
            return base.Channel.SetCar(request);
        }
        
        public void SetCar(double Capacity, int Id, string Model, int Passengers, CarClient.CarService.CarType Type, string Vendor, int Year) {
            CarClient.CarService.CarInfo inValue = new CarClient.CarService.CarInfo();
            inValue.Capacity = Capacity;
            inValue.Id = Id;
            inValue.Model = Model;
            inValue.Passengers = Passengers;
            inValue.Type = Type;
            inValue.Vendor = Vendor;
            inValue.Year = Year;
            CarClient.CarService.SetCarResponse retVal = ((CarClient.CarService.ICarService)(this)).SetCar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarClient.CarService.SetCarResponse> CarClient.CarService.ICarService.SetCarAsync(CarClient.CarService.CarInfo request) {
            return base.Channel.SetCarAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarClient.CarService.SetCarResponse> SetCarAsync(double Capacity, int Id, string Model, int Passengers, CarClient.CarService.CarType Type, string Vendor, int Year) {
            CarClient.CarService.CarInfo inValue = new CarClient.CarService.CarInfo();
            inValue.Capacity = Capacity;
            inValue.Id = Id;
            inValue.Model = Model;
            inValue.Passengers = Passengers;
            inValue.Type = Type;
            inValue.Vendor = Vendor;
            inValue.Year = Year;
            return ((CarClient.CarService.ICarService)(this)).SetCarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarClient.CarService.CarInfo CarClient.CarService.ICarService.GetCar(CarClient.CarService.CarRequest request) {
            return base.Channel.GetCar(request);
        }
        
        public double GetCar(string LicenseKey, ref int Id, out string Model, out int Passengers, out CarClient.CarService.CarType Type, out string Vendor, out int Year) {
            CarClient.CarService.CarRequest inValue = new CarClient.CarService.CarRequest();
            inValue.LicenseKey = LicenseKey;
            inValue.Id = Id;
            CarClient.CarService.CarInfo retVal = ((CarClient.CarService.ICarService)(this)).GetCar(inValue);
            Id = retVal.Id;
            Model = retVal.Model;
            Passengers = retVal.Passengers;
            Type = retVal.Type;
            Vendor = retVal.Vendor;
            Year = retVal.Year;
            return retVal.Capacity;
        }
        
        public System.Threading.Tasks.Task<CarClient.CarService.CarInfo> GetCarAsync(CarClient.CarService.CarRequest request) {
            return base.Channel.GetCarAsync(request);
        }
    }
}
